name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/co-habit-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/co-habit-frontend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    needs: docker
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Generate changelog
        run: echo "# New Release have arrived" > ${{ github.workspace }}-changelog.txt
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-changelog.txt
          token: ${{ secrets.GH_PAT }}
